const ADD_FAVORITE = "ADD_FAVORITE";
const DELETE_FAVORITE = "DELETE_FAVORITE";
const GET_FAV = "GET_FAV";
const FILTER = "FILTER";
const ORDER = "ORDER";

module.exports = {
  ADD_FAVORITE,
  DELETE_FAVORITE,
  GET_FAV,
  FILTER,
  ORDER,
};
